FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && \
    apt-get install -y \
        git \
        curl \
        unzip \
        build-essential && \
    rm -rf /var/lib/apt/lists/*
